# Generated by Django 5.0.6 on 2024-09-23 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='role',
        ),
    ]
