# Generated by Django 5.0.6 on 2024-10-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='createdAt',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
